exports.pi = Math.PI;
exports.e = Math.E;
exports.remainder = top => bottom => top % bottom;
exports.isFinite = isFinite;
exports.isNaN = isNaN;

exports.abs = Math.abs;
exports.acos = Math.acos;
exports.acosh = Math.acosh;
exports.asin = Math.asin;
exports.asinh = Math.asinh;
exports.atan = Math.atan;
exports.atan2 = y => x => Math.atan2(y, x);
exports.atanh = Math.atanh;
exports.cbrt = Math.cbrt;
exports.ceil = Math.ceil;
exports.clz32 = Math.clz32;
exports.cos = Math.cos;
exports.cosh = Math.cosh;
exports.exp = Math.exp;
exports.expm1 = Math.expm1;
exports.floor = Math.floor;
exports.fround = Math.fround;
exports.hypot = x => y => Math.hypot(x, y);
exports.imul = x => y => Math.imul(x, y);
exports.log = Math.log;
exports.log10 = Math.log10;
exports.log1p = Math.log1p;
exports.log2 = Math.log2;
exports.max = x => y => Math.max(x, y);
exports.min = x => y => Math.min(x, y);
exports.round = Math.round;
exports.sign = Math.sign;
exports.sin = Math.sin;
exports.sinh = Math.sinh;
exports.sqrt = Math.sqrt;
exports.tan = Math.tan;
exports.tanh = Math.tanh;
exports.trunc = Math.trunc;
